[train_config]
finetuning_type = 1
batch_size = 64
lr = 0.01
epochs = 2
use_scheduler = true
lr_decay_rate = 0.99
optimizer_weight_decay = 0.01
device = "cpu"
epoch_to_save_model = 10
path_to_save_model = "model_weights"
measure_metrics_during_training = true
print_var = true
seed = -1
wandb_training = false
project_name = "demnet_training"
model_artifact_name = "demnet"
log_freq = 1
name_training_run = ""
notes = ""
debug = true

[dataset_config]
merge_all_AD_class = false
load_data_in_memory = true
percentage_train = 0.8
percentage_validation = 0.1
percentage_test = 0.1
grey_scale_image = true
