[train_config]
batch_size = 64
lr = 0.01
epochs = 50
use_scheduler = true
lr_decay_rate = 0.95
optimizer_weight_decay = 0.01
device = "cuda"
epoch_to_save_model = 10
path_to_save_model = "model_weights"
measure_metrics_during_training = true
print_var = true
seed = -1
wandb_training = false
project_name = "demnet_training"
model_artifact_name = "demnet_training_AD_kaggle"
log_freq = 1
name_training_run = ""
notes = ""
debug = true

[dataset_config]
merge_all_AD_class = 0
load_data_in_memory = true
percentage_train = 0.7
percentage_validation = 0.15
percentage_test = 0.15
grey_scale_image = true
