path_dataset_config = "scripts_python/training_FL/ADNI_fedavg_with_wandb/config/dataset.toml"
path_data = "data/ADNI_axial_3D_z_48_size_176_int/"
name_tensor_file = "dataset_tensor___176_resize___int.pt"
merge_AD_class = 2
percentage_train = 0.7
percentage_test = 0.15
percentage_validation = 0.15
rescale_factor = 4095.0
apply_rescale = true
load_data_in_memory = false
use_normalization = true
