path_server_config = "scripts_python/training_FL/ADNI_demnet_fedavg_with_wandb_V2/config/server.toml"
num_rounds = 3
rounds_to_save_model = 4
num_clients = 3
fraction_fit = 1.0
fraction_evaluate = 1.0
clients_seed = [ "np.int64(1354153809)", "np.int64(885220583)", "np.int64(1896543432)",]
path_idx_server_data = "data/ADNI_axial_middle_slice/FL_idx/"
keep_labels_proportion = true
centralized_evaluation = true
use_on_fit_config_function = false
simulation = true

[wandb_config]
wandb_training = true
project_name = "demnet_training_ADNI_FL_V2"
entity = "alberto_zancanaro_academic"
model_artifact_name = "demnet_z_1"
log_freq = 1
metrics_to_log_from_clients = [ "accuracy_train accuracy_validation",]
log_model_artifact = true
debug = true
num_cpus = 4.0
num_gpus = 1.0
max_cpu_allowed = 4
max_gpu_allowed = 1
