path_server_config = "scripts_python/training_FL/ADNI_vgg_fedavg_with_wandb/config/server.toml"
num_rounds = 50
rounds_to_save_model = 51
n_client = 5
fraction_fit = 1.0
fraction_evaluate = 1.0
clients_seed = [ "np.int64(1198437650)", "np.int64(950632102)", "np.int64(1854673939)", "np.int64(1565231014)", "np.int64(1640280418)",]
keep_labels_proportion = true
centralized_evaluation = true
use_on_fit_config_function = false

[wandb_config]
wandb_training = true
project_name = "vgg_training_ADNI_FL"
entity = "alberto_zancanaro_academic"
model_artifact_name = "vgg_z_1"
log_freq = 1
metrics_to_log_from_clients = [ "accuracy_train accuracy_validation",]
log_model_artifact = false
debug = false
num_cpus = 4.0
num_gpus = 1.0
max_cpu_allowed = 4
max_gpu_allowed = 1
