batch_size = 128
lr = 0.001
epochs = 2
use_scheduler = true
device = "mps"
epoch_to_save_model = 3
path_to_save_model = "model_weights/debug_FL"
measure_metrics_during_training = true
print_var = true
seed = 38272372
wandb_training = false
notes = ""
log_freq = 1
debug = false
use_weights_with_lower_validation_error = true
fl_training = true
vgg_training = true
use_pretrained_vgg = true
use_vgg_normalization_values = false
vgg_training_mode = 1

[lr_scheduler_config]
name = "ExponentialLR"
gamma = 0.94

[optimizer_config]
lr = 0.001
name = "SGD"
momentum = 0.9
dampening = 0.0
nesterov = false
weight_decay = 1e-5
maximize = false
