batch_size = 128
lr = 0.001
epochs = 5
use_scheduler = true
device = "cuda"
epoch_to_save_model = 6
path_to_save_model = "model_weights/demnet_ADNI_FL/exp_lr_4328522"
measure_metrics_during_training = true
print_var = true
seed = 3623483892
wandb_training = false
notes = ""
log_freq = 1
debug = false
use_weights_with_lower_validation_error = true
fl_training = true

[lr_scheduler_config]
name = "ExponentialLR"
gamma = 0.9

[optimizer_config]
lr = 0.001
name = "AdamW"
betas = [ 0.9, 0.999,]
eps = 1e-8
weight_decay = 1e-5
amsgrad = false
maximize = false
